### ISSUE TITLE
Refused to display 'url' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'

### ISSUE THREAD

**Issue by habibaamri** [robbestad/react-iframe#57]

**Comment by jvrjosephlouie** [comment]
getting the same problem

**Comment by chrisbchrist** [comment]
This is not an issue with the package, it's because the owner of the webpage you are trying to display in the frame has configured its settings specifically to disallow usage in iframes.  Unfortunately, you will not be able to pull in that URL without the site owner's permission.  See [this SO answer](https://stackoverflow.com/questions/27358966/how-to-set-x-frame-options-on-iframe) for more information.

**Comment by MartinJesu** [comment]
Getting the same problem. Is there any tweak to achieve this from ReactJS perspective
